In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import numpy as np

In [2]:
df=pd.read_csv("loan_data.csv")
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [3]:
x=df.drop(columns='loan_status')
y=df.loan_status

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=42,train_size=0.8)

In [6]:
x.corr(numeric_only=True)

num_cols = x.select_dtypes(include='number').columns
obj_cols = x.select_dtypes(include='object').columns

C:\Users\lahar\AppData\Local\Temp\ipykernel_28356\494637197.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = x.select_dtypes(include='object').columns

In [7]:
x[obj_cols].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [9]:
onehot_col=['person_gender','person_home_ownership','loan_intent','previous_loan_defaults_on_file']
ordinal_col=['person_education']
order=['High School','Bachelor','Master','Associate','Doctorate']
print(df["person_education"].unique())
model=KNeighborsClassifier()
preprocessing=ColumnTransformer(
    transformers=[
        ('onehot',OneHotEncoder(handle_unknown='ignore',sparse_output=False),onehot_col),
        ('ordinal',OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),ordinal_col)
    ],
    remainder="passthrough"
)

<ArrowStringArray>
['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']
Length: 5, dtype: str

In [10]:
model=DecisionTreeClassifier(random_state=42)

In [11]:
main_pipeline=Pipeline([
    ('preprocessing',preprocessing),
    ('model',DecisionTreeClassifier(random_state=42))
])

In [12]:
grid_search_cv=GridSearchCV(
    estimator=main_pipeline,
    param_grid={
        'model__criterion':['gini','entropy'],
        'model__max_depth':[None,5,10,50,100],
        'model__min_samples_split':[2,5,7,10],
        'model__min_samples_leaf':[1,3,5,7,10],
        'model__splitter':['best','random']
    },
    verbose=1
)
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 400 candidates, totalling 2000 fits

GridSearchCV(estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('onehot',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['person_gender',
                                                                          'person_home_ownership',
                                                                          'loan_intent',
                                                                          'previous_loan_defaults_on_file']),
                                                                        ('ordinal',
                                                                         OrdinalEncoder(categories=[['High '
                                                                                                     'School',
                                                                                                     'Bachelor',
                                                                                                     'Master',
                                                                                                     'Asso...
                                                                                                     'Doctorate']],
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__max_depth': [None, 5, 10, 50, 100],
                         'model__min_samples_leaf': [1, 3, 5, 7, 10],
                         'model__min_samples_split': [2, 5, 7, 10],
                         'model__splitter': ['best', 'random']},
             verbose=1)

In [13]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['person_gender',
                                                   'person_home_ownership',
                                                   'loan_intent',
                                                   'previous_loan_defaults_on_file']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Master',
                                                                              'Associate',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(criterion='entropy', max_depth=10,
                                        random_state=42))])

In [14]:
grid_search_cv.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 10,
 'model__min_samples_leaf': 1,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [15]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.15043511, 0.07943692, 0.1258019 , 0.07744889, 0.12636557,
        0.0756566 , 0.12720499, 0.07485542, 0.12398381, 0.07584472,
        0.12216072, 0.07664785, 0.12658706, 0.07875633, 0.12938118,
        0.07800264, 0.12328143, 0.079878  , 0.13028278, 0.08633652,
        0.13703632, 0.08061471, 0.132938  , 0.08122764, 0.13221002,
        0.07889886, 0.13226976, 0.07818031, 0.12719078, 0.07801728,
        0.13828001, 0.07269664, 0.13586097, 0.0825707 , 0.13598261,
        0.07326794, 0.12990546, 0.07132502, 0.11611557, 0.07050633,
        0.08147545, 0.06320167, 0.07829437, 0.05893402, 0.07988205,
        0.05957828, 0.08178329, 0.06161976, 0.07950292, 0.05912361,
        0.08134789, 0.0610558 , 0.0826611 , 0.05991578, 0.0806757 ,
        0.05950284, 0.0811317 , 0.05970836, 0.07930956, 0.06362205,
        0.08356552, 0.06357336, 0.09829745, 0.073596  , 0.08181305,
        0.0687449 , 0.08488989, 0.0703577 , 0.09045286, 0.07011218,
        0.08520198, 0.0770587 , 0.10437794, 0.07498288, 0.09452395,
        0.07744555, 0.08619514, 0.06479492, 0.08418145, 0.05918427,
        0.10078974, 0.07639213, 0.10884418, 0.06522856, 0.10097213,
        0.06517167, 0.10301418, 0.06561284, 0.099968  , 0.06634703,
        0.09972806, 0.07096829, 0.09948182, 0.06629577, 0.10047569,
        0.06639638, 0.09859443, 0.06530595, 0.1033823 , 0.07006812,
        0.10267453, 0.06669302, 0.10183501, 0.06647296, 0.0999218 ,
        0.06844425, 0.10214405, 0.06649928, 0.10688128, 0.06919708,
        0.09970937, 0.06606178, 0.10025272, 0.06672525, 0.09891415,
        0.06659222, 0.10333071, 0.06591654, 0.09980083, 0.06625018,
        0.12540431, 0.07738857, 0.12564139, 0.07739062, 0.12541924,
        0.07558565, 0.12345858, 0.07438016, 0.12288847, 0.07289128,
        0.12193608, 0.07539325, 0.12149744, 0.07554235, 0.12218456,
        0.07409439, 0.12600021, 0.07364068, 0.12175636, 0.07453108,
        0.13500485, 0.08008175, 0.1244875 , 0.0776166 , 0.1305902 ,
        0.07690754, 0.12062058, 0.07876859, 0.12739468, 0.08996   ,
        0.13697977, 0.08805285, 0.13381371, 0.07970767, 0.13113832,
        0.07509565, 0.13658175, 0.09076581, 0.1359333 , 0.08194356,
        0.14541688, 0.09156046, 0.14111729, 0.0797832 , 0.14002461,
        0.08659616, 0.1322216 , 0.08492532, 0.13556809, 0.08296599,
        0.13943844, 0.07794366, 0.12890959, 0.07979722, 0.13282294,
        0.07765846, 0.12908697, 0.07943139, 0.1322504 , 0.07675633,
        0.12684655, 0.09648037, 0.12502098, 0.07921686, 0.12683539,
        0.07477756, 0.12626204, 0.07442584, 0.12414017, 0.07432308,
        0.1243979 , 0.07633634, 0.12307878, 0.07514577, 0.12307906,
        0.07538481, 0.12657895, 0.0760778 , 0.1238276 , 0.07671952,
        0.15133243, 0.0841897 , 0.1488749 , 0.08139071, 0.14719372,
        0.07998271, 0.1463799 , 0.07937441, 0.14476771, 0.08304977,
        0.14295516, 0.08012094, 0.14033318, 0.0761097 , 0.13707719,
        0.07664528, 0.1377769 , 0.07650843, 0.13441472, 0.07854199,
        0.13727098, 0.07455153, 0.1349997 , 0.07557197, 0.13258986,
        0.07492814, 0.13320112, 0.07481894, 0.13358669, 0.07421126,
        0.13415771, 0.07542024, 0.13088326, 0.07257051, 0.13250794,
        0.07473598, 0.13701878, 0.07886281, 0.13995271, 0.07627468,
        0.08868756, 0.06825719, 0.09530325, 0.0630569 , 0.09452634,
        0.06889935, 0.10189481, 0.07068467, 0.09889908, 0.07113018,
        0.09331365, 0.07419753, 0.09653525, 0.08462539, 0.12094603,
        0.07849841, 0.12022614, 0.07521081, 0.11266155, 0.080125  ,
        0.09962163, 0.08897786, 0.10866032, 0.07952375, 0.09746809,
        0.10193529, 0.13609519, 0.095435  , 0.10993357, 0.07672896,
        0.11423607, 0.08120155, 0.12017016, 0.08236966, 0.10523319,
        0.07760701, 0.10984998, 0.08235483, 0.11884599, 0.08423996,
        0.15191865, 0.09916606, 0.12811165, 0.08630314, 0.13878474,
        0.08409972, 0.13137684, 0.08415613, 0.14570332, 0.08274784,
        0.14140072, 0.08394933, 0.13254766, 0.07853255, 0.11857238,
        0.08156786, 0.1910418 , 0.15233412, 0.2248136 , 0.11347866,
        0.17404308, 0.09556627, 0.14207191, 0.09550605, 0.12453151,
        0.10090919, 0.14085383, 0.08237638, 0.14598303, 0.09059525,
        0.15608296, 0.08675303, 0.13864555, 0.08397703, 0.14285064,
        0.0780973 , 0.12195907, 0.08527651, 0.11873274, 0.07515821,
        0.16323776, 0.0943522 , 0.18507867, 0.11825957, 0.16198096,
        0.09131575, 0.19130311, 0.10257668, 0.18143907, 0.09997349,
        0.19596848, 0.09711204, 0.18524985, 0.09720106, 0.15125756,
        0.0836483 , 0.14238105, 0.08179536, 0.14633694, 0.08826246,
        0.18054256, 0.10029273, 0.16929789, 0.08606181, 0.18582182,
        0.09841332, 0.19260073, 0.10853896, 0.18574595, 0.08649774,
        0.14671931, 0.08796387, 0.14557619, 0.10040002, 0.16774688,
        0.0961441 , 0.18104115, 0.09184446, 0.16040392, 0.08841276,
        0.17503428, 0.09383602, 0.16409049, 0.12469049, 0.19680429,
        0.12761588, 0.2133781 , 0.11490278, 0.16111846, 0.08817091,
        0.1585712 , 0.09052949, 0.14697723, 0.08328671, 0.14326386,
        0.07644377, 0.13674412, 0.08109684, 0.14500823, 0.0900434 ,
        0.18822684, 0.08689485, 0.15221214, 0.09791594, 0.1843421 ,
        0.10069447, 0.17264042, 0.09824467, 0.17053185, 0.09376841,
        0.17461658, 0.10695405, 0.17093592, 0.09205999, 0.17184772,
        0.09060249, 0.15110383, 0.09952178, 0.18056002, 0.11936483]),
 'std_fit_time': array([0.02034179, 0.00394839, 0.00226414, 0.00377887, 0.01009641,
        0.00118461, 0.00275124, 0.00158333, 0.0008341 , 0.00264532,
        0.00277881, 0.00169617, 0.00268936, 0.00223394, 0.01636499,
        0.00933579, 0.00210323, 0.00881851, 0.00915766, 0.01137306,
        0.01201349, 0.00681673, 0.00810384, 0.00700163, 0.01621056,
        0.00868462, 0.0217501 , 0.00683923, 0.01039389, 0.0059984 ,
        0.01980527, 0.00160412, 0.02969456, 0.01042094, 0.01427321,
        0.0019658 , 0.01344104, 0.00207852, 0.00191064, 0.00111953,
        0.00242622, 0.00265816, 0.00168588, 0.00146655, 0.00241302,
        0.00159804, 0.00644342, 0.00644775, 0.00159081, 0.00129073,
        0.00359946, 0.00229763, 0.0021015 , 0.00126039, 0.00124714,
        0.00116577, 0.0022746 , 0.00092532, 0.00103478, 0.00852353,
        0.00576182, 0.00391808, 0.01299778, 0.0157311 , 0.00226305,
        0.00826908, 0.00831447, 0.01370058, 0.01083501, 0.01213129,
        0.00371934, 0.01484785, 0.01681856, 0.01320092, 0.0187199 ,
        0.01407634, 0.01631408, 0.00554501, 0.00846362, 0.00105957,
        0.00433366, 0.013027  , 0.01029381, 0.00143304, 0.00309042,
        0.00128396, 0.00376007, 0.00063372, 0.00326307, 0.00262779,
        0.00158868, 0.00696728, 0.00063822, 0.00124837, 0.00105243,
        0.00394412, 0.00171933, 0.00154701, 0.0086792 , 0.00894335,
        0.0035329 , 0.00121192, 0.00218784, 0.00115715, 0.00255893,
        0.00428383, 0.00500925, 0.00149212, 0.01140475, 0.00650079,
        0.00261464, 0.00213576, 0.0022198 , 0.00161802, 0.00156958,
        0.00137027, 0.00124288, 0.00073872, 0.00201577, 0.00142839,
        0.00236837, 0.00371425, 0.00198101, 0.0039238 , 0.00219413,
        0.0017947 , 0.00208902, 0.00070665, 0.00265793, 0.0019372 ,
        0.002541  , 0.001988  , 0.00176346, 0.00126636, 0.00225229,
        0.00214234, 0.00330849, 0.0022625 , 0.0029693 , 0.00186091,
        0.01789257, 0.0127269 , 0.00587135, 0.00600662, 0.01710075,
        0.00757932, 0.00515306, 0.0102075 , 0.00651174, 0.0276139 ,
        0.01161478, 0.01462329, 0.01574051, 0.01441192, 0.01135127,
        0.0015357 , 0.0195639 , 0.01420258, 0.01514402, 0.01336944,
        0.01537368, 0.01391965, 0.00787349, 0.00306115, 0.00921158,
        0.0125676 , 0.00375117, 0.00619113, 0.01142327, 0.00530469,
        0.01283402, 0.00185009, 0.00215038, 0.00370924, 0.00231088,
        0.00338168, 0.00263267, 0.00455449, 0.01112901, 0.00118233,
        0.00622384, 0.01737218, 0.00090436, 0.00267842, 0.00403116,
        0.00172761, 0.00434271, 0.0010236 , 0.00118838, 0.00122511,
        0.00158336, 0.0011825 , 0.00506158, 0.00221253, 0.00442598,
        0.00135789, 0.00246122, 0.00120514, 0.00271256, 0.00310663,
        0.00443128, 0.00144048, 0.00414123, 0.00149066, 0.002867  ,
        0.00114498, 0.00363521, 0.00111736, 0.00064665, 0.00392462,
        0.00317148, 0.00092606, 0.00218762, 0.00136865, 0.00223659,
        0.00111079, 0.0029512 , 0.00044283, 0.0011631 , 0.00244279,
        0.00438939, 0.00132738, 0.0019602 , 0.0019512 , 0.00179229,
        0.00169014, 0.00104044, 0.0010761 , 0.00186977, 0.00099527,
        0.00273665, 0.00184138, 0.00235404, 0.00076613, 0.00365826,
        0.00267002, 0.00664082, 0.00721868, 0.009999  , 0.00301728,
        0.00444082, 0.0127375 , 0.01093712, 0.00218885, 0.00987122,
        0.00547385, 0.01601925, 0.01466736, 0.01080366, 0.00684374,
        0.00783616, 0.01849393, 0.01043588, 0.01802196, 0.01455902,
        0.00944423, 0.010377  , 0.00835019, 0.01468026, 0.01402253,
        0.00672457, 0.01253068, 0.01242477, 0.01384516, 0.00237569,
        0.03743445, 0.01332816, 0.01656533, 0.00374043, 0.00206418,
        0.01203809, 0.00959419, 0.00920705, 0.00313245, 0.00216373,
        0.01409471, 0.00744561, 0.01053478, 0.01615515, 0.00871875,
        0.02220942, 0.01435482, 0.00771214, 0.00646657, 0.01079059,
        0.00713316, 0.01521882, 0.00715776, 0.01550284, 0.00329207,
        0.01326957, 0.01154248, 0.01494962, 0.00367464, 0.00296767,
        0.01250531, 0.02384166, 0.01361943, 0.02945965, 0.00275748,
        0.0267482 , 0.0101433 , 0.00616756, 0.01259488, 0.00649502,
        0.01254642, 0.00976506, 0.00183691, 0.01908429, 0.00787471,
        0.0084997 , 0.00406957, 0.01361267, 0.00439657, 0.01002178,
        0.0042719 , 0.0127093 , 0.01326351, 0.00199353, 0.00495847,
        0.00858415, 0.00331181, 0.02667399, 0.02429142, 0.00644276,
        0.00627558, 0.02080067, 0.01426919, 0.01671255, 0.01368207,
        0.01951677, 0.00413916, 0.02342899, 0.01008151, 0.00229999,
        0.00268626, 0.00225346, 0.00422366, 0.0033673 , 0.01624676,
        0.01467065, 0.01502154, 0.0121053 , 0.0019975 , 0.01206921,
        0.01562468, 0.0252439 , 0.01567672, 0.01664299, 0.00526217,
        0.00472089, 0.00801743, 0.0044018 , 0.01904978, 0.00888496,
        0.01950324, 0.01795512, 0.01540729, 0.00751841, 0.0108969 ,
        0.01854484, 0.0040816 , 0.00756154, 0.01614984, 0.01527713,
        0.01842301, 0.02222974, 0.01742501, 0.00572091, 0.00685527,
        0.00612955, 0.00344555, 0.00257204, 0.0039544 , 0.00352188,
        0.00086187, 0.00491646, 0.00133499, 0.00213732, 0.01121886,
        0.01889067, 0.00421665, 0.00553298, 0.00894293, 0.01144659,
        0.00637416, 0.00947998, 0.01545361, 0.01090482, 0.00800813,
        0.00997713, 0.01354222, 0.01159309, 0.00916108, 0.01106803,
        0.00710351, 0.01222817, 0.01153832, 0.01350779, 0.04026667]),
 'mean_score_time': array([0.01425333, 0.01284146, 0.01288819, 0.01414261, 0.01453342,
        0.01317677, 0.01381941, 0.01288762, 0.01267247, 0.01226931,
        0.01318727, 0.01271362, 0.01386514, 0.01360755, 0.01264291,
        0.01226072, 0.01311345, 0.01705279, 0.01423101, 0.01505189,
        0.01805406, 0.01209793, 0.01911149, 0.0147438 , 0.01266561,
        0.013693  , 0.01223373, 0.01444855, 0.01250653, 0.01370749,
        0.01618371, 0.01262398, 0.01436543, 0.01628118, 0.01564736,
        0.01270094, 0.01433511, 0.0129179 , 0.01270242, 0.01140904,
        0.01265006, 0.01420588, 0.01230221, 0.01210656, 0.01266065,
        0.01215734, 0.01296892, 0.01351852, 0.01286702, 0.01207085,
        0.01240597, 0.01332917, 0.01292043, 0.01247153, 0.01225929,
        0.01244125, 0.0128726 , 0.01302781, 0.01189799, 0.01434498,
        0.01522694, 0.01723375, 0.0137352 , 0.01521997, 0.01237621,
        0.01443305, 0.0139647 , 0.01412702, 0.0187995 , 0.01625743,
        0.01372743, 0.01882901, 0.01534228, 0.01454625, 0.01345053,
        0.0139359 , 0.012995  , 0.0146132 , 0.01312799, 0.01201825,
        0.01382337, 0.01377759, 0.01352682, 0.01868377, 0.01284747,
        0.01222987, 0.01263056, 0.01294065, 0.0133688 , 0.01265202,
        0.01260405, 0.01581259, 0.0121254 , 0.01310716, 0.01221724,
        0.01218214, 0.01205444, 0.01257377, 0.01289701, 0.01480393,
        0.01298852, 0.01235328, 0.01205988, 0.01227474, 0.01539907,
        0.01264329, 0.01441259, 0.01289854, 0.01215334, 0.01266384,
        0.01222534, 0.012958  , 0.01261525, 0.01292601, 0.01229701,
        0.01240616, 0.01204381, 0.01262212, 0.01184926, 0.01264338,
        0.01221232, 0.01314783, 0.01299043, 0.01355391, 0.01269174,
        0.01268511, 0.01218171, 0.01277261, 0.01237035, 0.01160884,
        0.01349654, 0.01244426, 0.01277442, 0.01253262, 0.01262894,
        0.01262951, 0.0137383 , 0.0130414 , 0.01249642, 0.01305814,
        0.01435342, 0.01338906, 0.01281085, 0.01468124, 0.0134871 ,
        0.01376109, 0.01207108, 0.01566281, 0.01480956, 0.01447549,
        0.01433096, 0.01317325, 0.0148797 , 0.01262865, 0.01777258,
        0.01322117, 0.01588254, 0.0141304 , 0.01466422, 0.01287889,
        0.01677947, 0.01571851, 0.01496229, 0.01336341, 0.01641827,
        0.01425767, 0.01279826, 0.01283312, 0.01267071, 0.01460295,
        0.01290226, 0.01348801, 0.01323581, 0.01352859, 0.01292624,
        0.01422601, 0.01296625, 0.01391845, 0.01283021, 0.01307416,
        0.01542993, 0.01448097, 0.01286874, 0.0128438 , 0.01365442,
        0.01296911, 0.01293492, 0.01306071, 0.01327443, 0.01238399,
        0.01321359, 0.01288157, 0.01385837, 0.01293426, 0.01299195,
        0.01282983, 0.01269255, 0.01305819, 0.01342483, 0.01347136,
        0.0140862 , 0.01392932, 0.01316943, 0.01290121, 0.013381  ,
        0.01292391, 0.01345615, 0.01257048, 0.01308045, 0.0136126 ,
        0.01335373, 0.0137907 , 0.01254668, 0.01293864, 0.01385293,
        0.01346197, 0.01303396, 0.01314425, 0.01246958, 0.01283789,
        0.01268525, 0.0130075 , 0.01311703, 0.01307435, 0.01365147,
        0.01288114, 0.01273322, 0.01334953, 0.01283693, 0.01363373,
        0.01345868, 0.01353726, 0.01266332, 0.01245556, 0.01297016,
        0.01341696, 0.01394954, 0.01634679, 0.01391597, 0.01331086,
        0.01285453, 0.01351819, 0.01695094, 0.01605735, 0.01427546,
        0.01634407, 0.01585612, 0.01659832, 0.01404428, 0.01395922,
        0.01383257, 0.01444755, 0.01450715, 0.01619496, 0.01746402,
        0.01665354, 0.01756544, 0.01443067, 0.01893535, 0.01795812,
        0.01482353, 0.02014785, 0.01533461, 0.01648259, 0.01412511,
        0.01976194, 0.02256889, 0.01968551, 0.01581693, 0.01539578,
        0.01736493, 0.01553807, 0.01840587, 0.01686864, 0.01489234,
        0.01444087, 0.01778231, 0.01567416, 0.01707296, 0.01557641,
        0.01710186, 0.01659479, 0.01428089, 0.01716971, 0.01935682,
        0.01537719, 0.01501107, 0.01775265, 0.01664157, 0.01462808,
        0.01461878, 0.01592317, 0.01410761, 0.01473775, 0.01488042,
        0.01500192, 0.01845174, 0.03101678, 0.02403579, 0.01982045,
        0.02352648, 0.01582475, 0.01815515, 0.018961  , 0.01626458,
        0.01824799, 0.01815248, 0.01593523, 0.01787362, 0.01603484,
        0.01855836, 0.01729426, 0.01472154, 0.01541977, 0.01712484,
        0.0138052 , 0.01448703, 0.01604738, 0.01430912, 0.01581187,
        0.01495562, 0.01434536, 0.02010174, 0.0186162 , 0.01432643,
        0.01488738, 0.01908598, 0.01906457, 0.01941094, 0.01811233,
        0.01960249, 0.01652656, 0.01584964, 0.01571231, 0.01438742,
        0.01332874, 0.01370611, 0.01350574, 0.01325507, 0.01565661,
        0.0190042 , 0.01785841, 0.01597366, 0.01557121, 0.02257552,
        0.01557264, 0.02043548, 0.01750574, 0.01881652, 0.01466479,
        0.01434941, 0.01873527, 0.01401815, 0.02142859, 0.01507311,
        0.01463599, 0.02087517, 0.01683421, 0.01665621, 0.01530313,
        0.0191597 , 0.01500854, 0.01605067, 0.02256823, 0.020046  ,
        0.01923819, 0.02158055, 0.0166141 , 0.01393566, 0.01358924,
        0.01421375, 0.01427846, 0.01330285, 0.01405592, 0.0132298 ,
        0.01290617, 0.01388068, 0.01404705, 0.01324277, 0.0136075 ,
        0.01877079, 0.01517897, 0.01434927, 0.01873221, 0.01544027,
        0.01913991, 0.01554613, 0.01608939, 0.0149312 , 0.01481647,
        0.01793475, 0.01930909, 0.01616855, 0.01731253, 0.01819549,
        0.01535392, 0.01869583, 0.01594377, 0.01896892, 0.01993747]),
 'std_score_time': array([2.24914556e-03, 8.86466196e-04, 2.46648186e-04, 1.76182559e-03,
        3.51091082e-03, 3.91145676e-04, 1.40105419e-03, 6.04045421e-04,
        5.58599709e-04, 8.47527036e-04, 8.29014671e-04, 8.15254033e-04,
        1.23179442e-03, 4.60624334e-04, 5.00332381e-04, 5.84999042e-04,
        3.48313744e-04, 9.02454109e-03, 7.92006530e-04, 3.78375311e-03,
        6.05325175e-03, 8.29171209e-04, 7.55191799e-03, 3.81470856e-03,
        9.01578482e-04, 1.79787348e-03, 5.94120347e-04, 2.41219953e-03,
        6.21415264e-04, 1.36175627e-03, 4.73089737e-03, 8.19643149e-04,
        3.10297804e-03, 2.89802499e-03, 4.56862068e-03, 9.57738259e-04,
        2.61210525e-03, 9.54212962e-04, 6.15792635e-04, 7.73339613e-05,
        6.10481010e-04, 1.50128202e-03, 7.64433402e-04, 6.31118083e-04,
        6.43254415e-04, 6.54307994e-04, 2.02022818e-03, 2.99771707e-03,
        8.91673927e-04, 7.97305557e-04, 1.13783773e-03, 9.13068474e-04,
        7.38023568e-04, 5.91639431e-04, 9.09798193e-04, 4.74360246e-04,
        7.35942082e-04, 8.53589507e-04, 4.55214171e-04, 3.00988455e-03,
        4.81568957e-03, 5.80404973e-03, 1.60366331e-03, 4.18304191e-03,
        7.66455841e-04, 3.36038154e-03, 4.58852989e-03, 1.82939267e-03,
        7.30332566e-03, 5.35639300e-03, 3.31642069e-03, 6.58014370e-03,
        4.52221291e-03, 2.35882223e-03, 2.37213341e-03, 2.44065076e-03,
        1.59496432e-03, 4.62183719e-03, 1.38050421e-03, 3.79188614e-04,
        2.65710227e-03, 3.57009686e-03, 1.05715498e-03, 1.20663900e-02,
        4.47280509e-04, 9.25840237e-04, 1.19015111e-03, 1.08133051e-03,
        1.02996242e-03, 1.01392647e-03, 8.40719143e-04, 6.04619162e-03,
        7.53651478e-04, 7.70898765e-04, 8.78363069e-04, 2.76584814e-04,
        6.03120275e-04, 5.89286781e-04, 6.66649249e-04, 4.74946674e-03,
        1.92013531e-04, 7.54230211e-04, 8.08583490e-04, 5.08227753e-04,
        5.50574276e-03, 6.44451821e-04, 3.51436367e-03, 6.81408584e-04,
        7.44402237e-04, 5.18247082e-04, 5.02282966e-04, 1.68800583e-04,
        1.05182062e-03, 6.81068745e-04, 5.70101202e-04, 9.82599548e-04,
        8.33447825e-04, 6.13290057e-04, 5.08395486e-04, 5.24498558e-04,
        5.65049546e-04, 7.41716176e-04, 9.03502504e-04, 6.38449688e-04,
        9.12177220e-04, 5.29092039e-04, 8.34787530e-04, 4.78224724e-04,
        6.25975741e-04, 6.19969418e-04, 1.70022779e-03, 3.13891510e-04,
        4.54021907e-04, 4.74790487e-04, 7.51675071e-04, 8.21078792e-04,
        7.47100063e-04, 4.16155613e-04, 5.92829538e-04, 6.33154111e-04,
        4.34021268e-03, 2.54364851e-03, 5.78905656e-04, 2.59228029e-03,
        1.03020470e-03, 1.43838902e-03, 8.66513850e-04, 3.18849663e-03,
        3.97153547e-03, 2.11204080e-03, 2.55420297e-03, 1.36780912e-03,
        1.80597902e-03, 6.34756584e-04, 4.25069993e-03, 1.66393827e-03,
        3.54557431e-03, 2.00754170e-03, 2.08192935e-03, 1.24746617e-03,
        4.99182925e-03, 3.10989451e-03, 4.62396885e-03, 7.09912871e-04,
        4.19458449e-03, 2.98686370e-03, 5.46180017e-04, 8.96586297e-04,
        6.06865827e-04, 1.79397292e-03, 6.40283595e-04, 1.16911295e-03,
        4.40062910e-04, 1.05582143e-03, 5.78995101e-04, 1.44281464e-03,
        1.27107911e-03, 1.24048269e-03, 9.07265324e-04, 8.57276417e-04,
        3.86344411e-03, 1.94081956e-03, 8.29692868e-04, 1.06004677e-03,
        1.16003588e-03, 1.01775642e-03, 8.88621208e-04, 8.09555214e-04,
        7.22512121e-04, 5.33552770e-04, 4.78345759e-04, 1.38670638e-03,
        5.44544222e-04, 3.54346332e-04, 9.59508827e-04, 3.32854449e-04,
        7.24744554e-04, 9.43449678e-04, 7.20326180e-04, 1.01703307e-03,

In [16]:
results=pd.DataFrame(grid_search_cv.cv_results_)

In [17]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
280,0.151919,0.022209,0.017102,0.003037,entropy,10,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.918889,0.925972,0.914861,0.921111,0.920833,0.920333,0.003597,1
302,0.142072,0.006168,0.018155,0.003356,entropy,10,5,10,best,"{'model__criterion': 'entropy', 'model__max_de...",0.917917,0.927361,0.914444,0.921250,0.920417,0.920278,0.004260,2
298,0.224814,0.029460,0.024036,0.001976,entropy,10,5,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.917917,0.927361,0.914444,0.921250,0.920417,0.920278,0.004260,2
300,0.174043,0.026748,0.023526,0.005410,entropy,10,5,7,best,"{'model__criterion': 'entropy', 'model__max_de...",0.917917,0.927361,0.914444,0.921250,0.920417,0.920278,0.004260,2
282,0.128112,0.007712,0.014281,0.000583,entropy,10,1,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919028,0.925972,0.915000,0.920694,0.920694,0.920278,0.003527,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,0.068745,0.008269,0.014433,0.003360,gini,5,7,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872639,0.872417,0.000461,393
79,0.059184,0.001060,0.012018,0.000379,gini,5,10,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
77,0.064795,0.005545,0.014613,0.004622,gini,5,10,7,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
75,0.077446,0.014076,0.013936,0.002441,gini,5,10,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
73,0.074983,0.013201,0.014546,0.002359,gini,5,10,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397

In [18]:
ypred_test=grid_search_cv.predict(xtest)

In [19]:
print(classification_report(ytest,ypred_test))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      6990
           1       0.89      0.73      0.80      2010

    accuracy                           0.92      9000
   macro avg       0.91      0.85      0.88      9000
weighted avg       0.92      0.92      0.92      9000